import { RequestDataCacheType } from './index'

const PageRoutePrefix = 'search'

export const Search: RequestDataCacheType = {
  [`${PageRoutePrefix}/data`]: {
    code: 200,
    data: {
      total: 377,
      list: [
        {
          coverUrl: '',
          title: '手机维修，电脑重装，样样精通',
          type: 1,
          content: '电脑维修、拆装机、故障检测、硬件检测、刷机演示、案例分享',
          viewCount: 4147,
          commentCount: 213,
          collectionCount: 32,
          author: '灭霸小天才',
          avatar: 'https://cdn.cnbj1.fds.api.mi-img.com/hiui-template/resources/01.jpeg',
          publishTime: '2021/02/07 16:50:25',
        },
        {
          coverUrl: '',
          title: '手机维修，电脑重装，样样精通',
          type: 5,
          content: '电脑维修、拆装机、故障检测、硬件检测、刷机演示、案例分享',
          viewCount: 4147,
          commentCount: 213,
          collectionCount: 32,
          author: '灭霸小天才',
          avatar: 'https://cdn.cnbj1.fds.api.mi-img.com/hiui-template/resources/01.jpeg',
          publishTime: '2021/02/07 16:50:25',
        },
        {
          coverUrl:
            'https://cnbj1.fds.api.xiaomi.com/hiui-template/resources/workbench-cover-01.png',
          title: '手机维修，电脑重装，样样精通',
          type: 5,
          content: '电脑维修、拆装机、故障检测、硬件检测、刷机演示、案例分享',
          viewCount: 4147,
          commentCount: 213,
          collectionCount: 32,
          author: '灭霸小天才',
          avatar: 'https://cdn.cnbj1.fds.api.mi-img.com/hiui-template/resources/01.jpeg',
          publishTime: '2021/02/07 16:50:25',
        },
        {
          coverUrl:
            'https://cnbj1.fds.api.xiaomi.com/hiui-template/resources/workbench-cover-03.png',
          title: '手机维修，电脑重装，样样精通',
          type: 3,
          content: '电脑维修、拆装机、故障检测、硬件检测、刷机演示、案例分享',
          viewCount: 4147,
          commentCount: 213,
          collectionCount: 32,
          author: '灭霸小天才',
          avatar: 'https://cdn.cnbj1.fds.api.mi-img.com/hiui-template/resources/01.jpeg',
          publishTime: '2021/02/07 16:50:25',
        },
        {
          coverUrl: '',
          title: '手机维修，电脑重装，样样精通',
          type: 1,
          content: '电脑维修、拆装机、故障检测、硬件检测、刷机演示、案例分享',
          viewCount: 4147,
          commentCount: 213,
          collectionCount: 32,
          author: '灭霸小天才',
          avatar: 'https://cdn.cnbj1.fds.api.mi-img.com/hiui-template/resources/01.jpeg',
          publishTime: '2021/02/07 16:50:25',
        },
        {
          coverUrl: '',
          title: '手机维修，电脑重装，样样精通',
          type: 4,
          content: '电脑维修、拆装机、故障检测、硬件检测、刷机演示、案例分享',
          viewCount: 4147,
          commentCount: 213,
          collectionCount: 32,
          author: '灭霸小天才',
          avatar: 'https://cdn.cnbj1.fds.api.mi-img.com/hiui-template/resources/01.jpeg',
          publishTime: '2021/02/07 16:50:25',
        },
        {
          coverUrl: '',
          title: '手机维修，电脑重装，样样精通',
          type: 5,
          content: '电脑维修、拆装机、故障检测、硬件检测、刷机演示、案例分享',
          viewCount: 4147,
          commentCount: 213,
          collectionCount: 32,
          author: '灭霸小天才',
          avatar: 'https://cdn.cnbj1.fds.api.mi-img.com/hiui-template/resources/01.jpeg',
          publishTime: '2021/02/07 16:50:25',
        },
        {
          coverUrl: '',
          title: '手机维修，电脑重装，样样精通',
          type: 5,
          content: '电脑维修、拆装机、故障检测、硬件检测、刷机演示、案例分享',
          viewCount: 4147,
          commentCount: 213,
          collectionCount: 32,
          author: '灭霸小天才',
          avatar: 'https://cdn.cnbj1.fds.api.mi-img.com/hiui-template/resources/01.jpeg',
          publishTime: '2021/02/07 16:50:25',
        },
        {
          coverUrl:
            'https://cnbj1.fds.api.xiaomi.com/hiui-template/resources/workbench-cover-01.png',
          title: '手机维修，电脑重装，样样精通',
          type: 2,
          content: '电脑维修、拆装机、故障检测、硬件检测、刷机演示、案例分享',
          viewCount: 4147,
          commentCount: 213,
          collectionCount: 32,
          author: '灭霸小天才',
          avatar: 'https://cdn.cnbj1.fds.api.mi-img.com/hiui-template/resources/01.jpeg',
          publishTime: '2021/02/07 16:50:25',
        },
        {
          coverUrl: '',
          title: '手机维修，电脑重装，样样精通',
          type: 1,
          content: '电脑维修、拆装机、故障检测、硬件检测、刷机演示、案例分享',
          viewCount: 4147,
          commentCount: 213,
          collectionCount: 32,
          author: '灭霸小天才',
          avatar: 'https://cdn.cnbj1.fds.api.mi-img.com/hiui-template/resources/01.jpeg',
          publishTime: '2021/02/07 16:50:25',
        },
      ],
    },
  },
  [`${PageRoutePrefix}/recommend-data`]: {
    code: 200,
    data: {
      count: 10,
      list: [
        {
          id: 1,
          title: '智能家装',
        },
        {
          id: 2,
          title: '扫地',
        },
        {
          id: 3,
          title: '家用配件',
        },
        {
          id: 4,
          title: '扫地机配件',
        },
        {
          id: 5,
          title: '开关',
        },
        {
          id: 6,
          title: '家用',
        },
        {
          id: 7,
          title: '家用仪表',
        },
        {
          id: 8,
          title: '音响',
        },
        {
          id: 9,
          title: '家电',
        },
        {
          id: 10,
          title: '家用滤芯',
        },
      ],
    },
  },
}
